### ISSUE TITLE
Prepare installer-bundle to Dapr Runtime v1.9.0-rc.1

### ISSUE THREAD

**Issue by shaibarlev** [dapr/installer-bundle#16]
Dapr Runtime was updated to Dapr Runtime v1.9.0-rc.1  , [https://github.com/dapr/dapr/releases/tag/v1.9.0-rc.1](url)
Please update the installer-bundle.
When can I test this https://github.com/dapr/installer-bundle/issues/8 ?

**Comment by shivamkm07** [comment]
@shaibarlev It was released yesterday: https://github.com/dapr/installer-bundle/releases/tag/v1.9.0-rc.1

You should be able to test #8 now:

For private/local registry: [install-by-providing-a-docker-container-registry-url](https://github.com/dapr/cli/blob/master/README.md#install-by-providing-a-docker-container-registry-url)
> Note: For init in kubernetes use `-k` with `--image-registry` i.e. `dapr init -k --image-registry <YOUR_REGISTRY>`

For privately hosted helm charts: [use-private-helm-repository](https://github.com/dapr/cli/blob/master/README.md#use-private-helm-repository)
