### ISSUE TITLE
installer-buddle v1.13.1 and v1.13.2 upgrade

### ISSUE THREAD

**Issue by adrienndikumana** [dapr/installer-bundle#22]
Hello, 

New releases of Dapr v1.13.1 and v1.13.2 include major fixes for Dapr pubsub and other important improvements. Is there a timeline for installer-bundle releases for these new Dapr versions?

Thanks,
Adrien

**Comment by mikeee** [comment]
@adrienndikumana Hi Adrien! The releases have been tagged and built, let me know if you have any issues 👍 

https://github.com/dapr/installer-bundle/releases/tag/v1.13.1

https://github.com/dapr/installer-bundle/releases/tag/v1.13.2

**Comment by adrienndikumana** [comment]
Thanks @mikeee!!
