### ISSUE TITLE
Update to Dapr 1.7.2

### ISSUE THREAD

**Issue by shaibarlev** [dapr/installer-bundle#5]
Dapr Runtime was updated to  v1.7.2 https://github.com/dapr/dapr/pull/4547.
Please update the installer-bundle

**Comment by shivamkm07** [comment]
Done.  Please check https://github.com/dapr/installer-bundle/releases/tag/v1.7.2

**Comment by shaibarlev** [comment]
Looks good, worked on my test offline machine. I'm waiting for the local/private Helm/Kubernetes fix.
